opts_fixed: 
    # ksp
    ksp_type: cg
    ksp_max_it: 5000
    ksp_rtol: 1.0e-5
    ksp_divtol: 1.0e+10
    ksp_initial_guess_nonzero: False
    ksp_norm_type: unpreconditioned

    # pc
    pc_type: icc
    pc_factor_fill: 30
    pc_factor_mat_ordering_type: natural
    pc_factor_levels: 0
    pc_factor_shift_type: none

opts2learn:
  diagonal_shift:
    dim: 1
    ref: 0.1
    # the following is for parameter sensitivity analysis
    space: logspace
    start: -5
    end: 2
    steps: 100
    relative: True # only for diagonal shift
    
  
params4diff:
  delta: 1.0e-3
  type: full
  relative: True

debug: False